version: "3.0"

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: "demo"
      POSTGRES_MULTIPLE_DATABASES: "demo"
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./db_entrypoint.sh:/docker-entrypoint-initdb.d/db_entrypoint.sh

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 123456
#    volumes:
#      - pgadmin:/root/.pgadmin
    ports:
      - "8080:80"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST: db
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres-data:
    external: false
