# Generated by Django 3.1.7 on 2021-09-02 08:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('ACTIVATE', 'ACTIVATE'), ('INACTIVE', 'INACTIVE'), ('COMPLETE', 'COMPLETE')], default='ACTIVATE', max_length=20),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_customer', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('time_booked', models.DateTimeField(blank=True, null=True)),
                ('destination', models.TextField(blank=True, max_length=100, null=True)),
                ('number_seat', models.IntegerField(blank=True, null=True)),
                ('total_money', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('CANCELL', 'CANCELL'), ('INCOMPLETE', 'INCOMPLETE'), ('COMPLETE', 'COMPLETE')], default='INCOMPLETE', max_length=20)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.trip')),
            ],
            options={
                'db_table': 'ticket',
            },
        ),
    ]
