# Generated by Django 3.1.7 on 2021-08-23 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customer_employees'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='part',
            new_name='team',
        ),
        migrations.AlterField(
            model_name='employees',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
