# Generated by Django 3.1.7 on 2021-08-24 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210823_2301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='account_id',
            new_name='account',
        ),
        migrations.RenameField(
            model_name='employees',
            old_name='company_id',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='permission_id',
            new_name='permission',
        ),
        migrations.AlterField(
            model_name='employees',
            name='team',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
