# Generated by Django 3.1.7 on 2021-09-01 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210824_2243'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employees',
            options={'ordering': ['id']},
        ),
    ]
