# Generated by Django 3.1.7 on 2021-09-02 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210901_0927'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='account_id',
            new_name='account',
        ),
    ]
