# Generated by Django 3.1.7 on 2021-09-06 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210905_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
