# Generated by Django 3.1.7 on 2021-09-06 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210906_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='date_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
