# Generated by Django 3.1.7 on 2021-09-02 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_auto_20210902_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='province_begins',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='province_ends',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='StopPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVATE', 'ACTIVATE'), ('INACTIVE', 'INACTIVE')], default='ACTIVATE', max_length=20)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.route')),
            ],
            options={
                'db_table': 'stop_point',
                'ordering': ['route'],
            },
        ),
    ]
