# Generated by Django 3.1.7 on 2021-09-02 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_auto_20210902_1333'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyRoute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('UNouteLOCK', 'UNLOCK'), ('LOCK', 'LOCK')], default='UNouteLOCK', max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.route')),
            ],
            options={
                'db_table': 'company_route',
                'ordering': ['company'],
            },
        ),
    ]
