# Generated by Django 3.1.7 on 2021-09-02 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_companyroute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyroute',
            name='status',
            field=models.CharField(choices=[('ACTIVATE', 'ACTIVATE'), ('INACTIVE', 'INACTIVE')], default='ACTIVATE', max_length=20),
        ),
    ]
